name: CI

on:
  schedule:
    - cron: 0 18 * * *
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3

      # Set up BuildKit container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Login to container registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for vanilla
      # https://github.com/docker/metadata-action
      - name: Extract vanilla container image metadata
        id: meta-vanilla
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            suffix=-vanilla
          tags: |
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }},prefix=v
            type=raw,value=vanilla,suffix=
            type=raw,value=${{ github.sha }}
            type=edge,branch=master
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      # Extract metadata (tags, labels) for msr
      # https://github.com/docker/metadata-action
      - name: Extract msr container image metadata
        id: meta-msr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            suffix=-msr
          tags: |
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }},prefix=v
            type=raw,value=msr,suffix=
            type=raw,value=${{ github.sha }}
            type=edge,branch=master
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      # Build and push vanilla container image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push vanilla container image
        id: build-and-push-vanilla
        uses: docker/build-push-action@v6
        with:
          context: .
          file: vanilla-Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-vanilla.outputs.tags }}
          labels: ${{ steps.meta-vanilla.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push msr container image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push msr container image
        id: build-and-push-msr
        uses: docker/build-push-action@v6
        with:
          context: .
          file: msr-Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-msr.outputs.tags }}
          labels: ${{ steps.meta-msr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      # Sign the vanilla container image digest except on PRs.
      # This will only write to the public Rekor transparency log when the 
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the vanilla container image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta-vanilla.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-vanilla.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Sign the msr container image digest except on PRs.
      # This will only write to the public Rekor transparency log when the 
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the msr container image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta-msr.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-msr.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}


  vulnerability-scan:
    name: Vulnerability Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner against vanilla image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-vanilla
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results-vanilla.sarif
          # severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results for vanilla to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: vanilla
          sarif_file: trivy-results-vanilla.sarif

      - name: Run Trivy vulnerability scanner against msr image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-msr
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results-msr.sarif
          # severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results for msr to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: msr
          sarif_file: trivy-results-msr.sarif


  tagged-release:
    name: Tagged Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.event_name == 'push'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false